# Generated by Django 3.2.6 on 2021-08-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dance',
            name='descriptionOfDance',
        ),
        migrations.RemoveField(
            model_name='dance',
            name='nameOfDance',
        ),
        migrations.AddField(
            model_name='dance',
            name='description',
            field=models.TextField(default='descriptionOfDance', max_length=2500),
        ),
        migrations.AddField(
            model_name='dance',
            name='name',
            field=models.CharField(default='nameOfDance', max_length=100),
        ),
        migrations.AddField(
            model_name='dance',
            name='type',
            field=models.TextField(default='typeOfDance', max_length=100),
        ),
    ]
