# Generated by Django 3.2.6 on 2021-08-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dances', '0002_auto_20210825_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dance',
            name='description',
            field=models.TextField(default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='dance',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dance',
            name='type',
            field=models.TextField(default='', max_length=100),
        ),
    ]
