# Generated by Django 3.2.6 on 2021-09-01 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dances', '0005_alter_dancetype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Уладальнік'),
        ),
    ]
