# Generated by Django 3.2.6 on 2021-09-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dances', '0008_alter_dance_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dance',
            name='name',
            field=models.CharField(blank='True', max_length=100, null='True'),
        ),
    ]
