# Generated by Django 3.2.6 on 2021-09-20 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dances', '0010_alter_dance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Апісанне тыпу'),
        ),
        migrations.AlterField(
            model_name='dance',
            name='danceType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dances.dancetype', verbose_name='Тып танца'),
        ),
        migrations.AlterField(
            model_name='dance',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='Апісанне'),
        ),
        migrations.AlterField(
            model_name='dance',
            name='name',
            field=models.CharField(blank=True, default='Назва танца', max_length=100, verbose_name='Назва'),
        ),
    ]
