# Generated by Django 3.2.6 on 2021-10-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dances', '0012_bgimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgimg',
            name='img',
            field=models.ImageField(height_field='url_height', upload_to='bg_img', width_field='url_width'),
        ),
    ]
