# Generated by Django 3.2.6 on 2021-10-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dances', '0013_alter_bgimg_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgimg',
            name='img',
            field=models.ImageField(height_field=100, upload_to='bg_img', width_field=100),
        ),
    ]
