# Generated by Django 3.2.6 on 2021-10-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dances', '0015_alter_bgimg_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgimg',
            name='url_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgimg',
            name='url_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bgimg',
            name='img',
            field=models.ImageField(height_field='url_height', upload_to='bg_img', width_field='url_width'),
        ),
    ]
