# Generated by Django 3.2.6 on 2021-11-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dances', '0016_auto_20211013_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bgimg',
            new_name='MainPage',
        ),
    ]
