# Generated by Django 3.2.6 on 2021-11-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dances', '0019_dance_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancetype',
            name='dances',
            field=models.ManyToManyField(blank=True, to='dances.Dance', verbose_name='Танцы'),
        ),
    ]
