# Generated by Django 3.2.6 on 2021-11-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dances', '0021_auto_20211103_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Падтып танца')),
                ('description', models.TextField(blank=True, verbose_name='Апісанне')),
            ],
            options={
                'verbose_name': 'Падтып танца',
                'verbose_name_plural': 'Падтыпы танцаў',
            },
        ),
        migrations.AlterField(
            model_name='dance',
            name='description',
            field=models.TextField(blank=True, verbose_name='Апісанне'),
        ),
    ]
