# Generated by Django 3.2.6 on 2021-11-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dances', '0022_auto_20211103_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='dance',
            name='danceSubType',
            field=models.ManyToManyField(blank=True, to='dances.DanceSubType', verbose_name='Падтыпы танцаў'),
        ),
    ]
