# Generated by Django 3.2.6 on 2021-11-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dances', '0023_dance_dancesubtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DancePerfomance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Выкананне танца')),
                ('description', models.TextField(blank=True, verbose_name='Апісанне')),
            ],
            options={
                'verbose_name': 'Выкананне танца',
                'verbose_name_plural': 'Выкананні танцаў',
            },
        ),
        migrations.RemoveField(
            model_name='dance',
            name='danceSubType',
        ),
        migrations.DeleteModel(
            name='DanceSubType',
        ),
        migrations.AddField(
            model_name='dance',
            name='dancePerfomance',
            field=models.ManyToManyField(blank=True, to='dances.DancePerfomance', verbose_name='Выкананні танцаў'),
        ),
    ]
