# Generated by Django 3.2.6 on 2021-11-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dances', '0024_auto_20211103_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dance',
            old_name='dancePerfomance',
            new_name='dancePerfomances',
        ),
        migrations.AddField(
            model_name='danceperfomance',
            name='nameforHTML',
            field=models.CharField(default=123, max_length=40, verbose_name='Для HTML'),
            preserve_default=False,
        ),
    ]
